// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB2RV4v6-t4L9EsSnnuy2Bv1gz46f6m0nE',
    appId: '1:582587637:web:13102aca1acd52b7ede1bc',
    messagingSenderId: '582587637',
    projectId: 'georesolve-5e0ce',
    authDomain: 'georesolve-5e0ce.firebaseapp.com',
    storageBucket: 'georesolve-5e0ce.firebasestorage.app',
    measurementId: 'G-VXT7V2LFTV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAwIHxLSboRRaQwqYIPHHdpDXq4aXCD0eY',
    appId: '1:582587637:android:af3d83f2f48800d7ede1bc',
    messagingSenderId: '582587637',
    projectId: 'georesolve-5e0ce',
    storageBucket: 'georesolve-5e0ce.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCfep4SwhiLrAW_nDxpN5kyuUvPKS18OJQ',
    appId: '1:582587637:ios:47a7e0bd9cbd9ad6ede1bc',
    messagingSenderId: '582587637',
    projectId: 'georesolve-5e0ce',
    storageBucket: 'georesolve-5e0ce.firebasestorage.app',
    androidClientId: '582587637-boa7k4o6onp71i1j0224e5i03qj7tj15.apps.googleusercontent.com',
    iosClientId: '582587637-57jan85919jfh7vboaep6i1tei9gp65f.apps.googleusercontent.com',
    iosBundleId: 'com.example.geeresolve',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCfep4SwhiLrAW_nDxpN5kyuUvPKS18OJQ',
    appId: '1:582587637:ios:47a7e0bd9cbd9ad6ede1bc',
    messagingSenderId: '582587637',
    projectId: 'georesolve-5e0ce',
    storageBucket: 'georesolve-5e0ce.firebasestorage.app',
    androidClientId: '582587637-boa7k4o6onp71i1j0224e5i03qj7tj15.apps.googleusercontent.com',
    iosClientId: '582587637-57jan85919jfh7vboaep6i1tei9gp65f.apps.googleusercontent.com',
    iosBundleId: 'com.example.geeresolve',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB2RV4v6-t4L9EsSnnuy2Bv1gz46f6m0nE',
    appId: '1:582587637:web:13102aca1acd52b7ede1bc',
    messagingSenderId: '582587637',
    projectId: 'georesolve-5e0ce',
    authDomain: 'georesolve-5e0ce.firebaseapp.com',
    storageBucket: 'georesolve-5e0ce.firebasestorage.app',
    measurementId: 'G-VXT7V2LFTV',
  );
}
