name: geeresolve
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1
environment:
  sdk: ^3.8.1
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  animated_splash_screen: ^1.3.0
  camera: ^0.11.2
  supabase_flutter: ^2.9.1
  curved_bottom_navigation_bar: ^0.0.6
  introduction_screen: ^3.1.17
  firebase_auth: ^6.0.0
  firebase_core: ^4.0.0
  google_sign_in: ^6.1.15
  image_picker: ^1.1.2
  firebase_messaging: ^16.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/favicon.png
    - assets/images/loginPageTop.png
    - assets/images/loginpageBottom.png
    - assets/images/loginPage.png
    - assets/images/registerPage.png
    - assets/images/homePage.png
    - assets/images/status.png
    - assets/images/complaint.png
    - assets/images/complaintsPage.png
    - assets/images/defaultAvatar.png
    - assets/images/support.png
    - assets/images/statusPage.png
    - assets/images/faq.png